-- MySQL Script generated by MySQL Workbench
-- Sat Feb 24 15:09:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema simple_apm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simple_apm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple_apm` DEFAULT CHARACTER SET utf8 ;
USE `simple_apm` ;

-- -----------------------------------------------------
-- Table `simple_apm`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `simple_apm`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `group` INT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(50) NOT NULL,
  `appId` VARCHAR(60) NULL,
  `appSecret` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_application_group1_idx` (`group` ASC),
  CONSTRAINT `fk_application_group1`
    FOREIGN KEY (`group`)
    REFERENCES `simple_apm`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `simple_apm`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `application` INT NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 = OK\n1 = Warning\n2 = Error',
  `data` TEXT NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_application_idx` (`application` ASC),
  CONSTRAINT `fk_post_application`
    FOREIGN KEY (`application`)
    REFERENCES `simple_apm`.`application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `simple_apm`.`defaults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`defaults` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `simple_apm`.`threshold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`threshold` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `postPath` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 = OK\n1 = Warning\n2 = Error',
  `value` DECIMAL(10,6) NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `simple_apm`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `failedLoginCount` TINYINT NOT NULL DEFAULT 0,
  `lastLogin` DATETIME NULL,
  `lastActive` DATETIME NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `permissions` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `simple_apm`.`http`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_apm`.`http` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `path` VARCHAR(255) NOT NULL,
  `min` INT(11) NOT NULL DEFAULT 0 COMMENT 'in ms',
  `max` INT(11) NOT NULL DEFAULT 0 COMMENT 'in ms',
  `avg` INT(11) NOT NULL DEFAULT 0 COMMENT 'in ms',
  `count` INT(11) NOT NULL DEFAULT 0,
  `method` VARCHAR(10) NOT NULL,
  `application` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_http_application1_idx` (`application` ASC),
  CONSTRAINT `fk_http_application1`
    FOREIGN KEY (`application`)
    REFERENCES `simple_apm`.`application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
